# Generated by Django 4.1.5 on 2023-01-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist_name',
            field=models.ManyToManyField(to='zing_it.playlist'),
        ),
    ]
