# Generated by Django 4.1.5 on 2023-01-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0002_song_playlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist_name',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=50),
        ),
    ]
